Enhance out of stock message
rapidez/checkout-theme pull request #144
Opened 2024-11-14 09:58 UTC by JimmyHoenderdaal

2024-11-14 10:26 UTC, Roene-JustBetter approved these changes

2024-11-14 10:47 UTC, BobWez98 requested changes

2024-11-14 10:47 UTC, BobWez98 commented on resources/views/cart/partials/product/description.blade.php
> +            <div v-if="!canOrderCartItem(item)" class="text-ct-error text-balance bg-ct-error/5 my-2 max-w-sm p-2">
Please replace the v-if with this check; https://github.com/rapidez/core/pull/627/files#diff-9da9c7eb5d8ffc35371000ac0ceb2c0f5b43725a9dfc4312be677e84a22cf3dbR18

2024-11-14 10:47 UTC, BobWez98 commented on resources/views/cart/partials/product/image.blade.php
> +        v-bind:class="{'opacity-20' : !canOrderCartItem(item)}"
Replace with 
```suggestion
        v-bind:class="{'opacity-20' : !item.is_available}"
```

2024-11-15 10:20 UTC, jordythevulder submitted a review, later dismissed

2024-11-18 07:26 UTC, Roene-JustBetter submitted a review, later dismissed

2024-11-20 13:57 UTC, royduin commented
Conflicts 😇

2024-12-03 13:27 UTC, Roene-JustBetter approved these changes

2024-12-04 13:16 UTC, BobWez98 approved these changes

2024-12-05 08:13 UTC, royduin commented on resources/views/cart/partials/product/description.blade.php
> +            <div v-if="!item.is_available" class="text-ct-error text-balance bg-ct-error/5 my-2 max-w-sm p-2">
balance?

2024-12-05 08:13 UTC, royduin commented on resources/views/cart/partials/product/price.blade.php
> +    </template>
Do we want this?

2024-12-18 09:38 UTC, closed without merging