[3.x] Check for label in select input
rapidez/checkout-theme pull request #150
Opened 2024-12-05 14:25 UTC by Jade-GG

We check for it [in the other inputs](https://github.com/rapidez/checkout-theme/blob/master/resources/views/components/input/index.blade.php), so we should check here as well. Otherwise you may get an empty label with a star in it if the input is required, for example.

2024-12-12 14:49 UTC, indykoning approved these changes

2024-12-12 16:32 UTC, royduin commented
Don't we need the components from `rapidez/blade-components` here?

2024-12-13 07:42 UTC, Roene-JustBetter commented
> Don't we need the components from `rapidez/blade-components` here?

Yes @Jade-GG can you update this Pull request.

2024-12-13 07:43 UTC, Roene-JustBetter requested changes
Make use of the `rapidez/blade-components`

2024-12-13 09:05 UTC, closed without merging