Add newsletter to checkout success
rapidez/checkout-theme pull request #60
Opened 2023-12-14 14:30 UTC by Jade-GG

Because it doesn't really make sense to have a checkbox for the guest checkout (you can't un-subscribe as a guest with a graphql query), so I've replaced the guest checkout version with the textbox+register button that you'd normally find in the footer.

2023-12-15 09:08 UTC, royduin commented on resources/views/components/newsletter/once.blade.php
Once?

2023-12-15 09:42 UTC, jordythevulder commented on resources/views/components/newsletter/once.blade.php
> +                        <x-heroicon-o-arrow-path
<div elements are not allowed inside <button elements, only phase through elements. Can you resolve that?

2023-12-15 09:50 UTC, Jade-GG commented on resources/views/components/newsletter/once.blade.php
kon geen betere naam verzinnen, misschien is gewoon `input` beter ofzo 😅

2023-12-15 10:13 UTC, Jade-GG commented on resources/views/components/newsletter/input.blade.php
I've now divided up this file into a few different parts based on feedback from @Roene-JustBetter

Basically, all of the parts with logic have been taken out. Not sure if this is the best way to go, we could also split out the parts you might want to edit more often (like the title and button) but it seems a little psychotic to me to have one partial component for a single title.

2023-12-20 09:38 UTC, royduin commented
`mutation-button-text`? `input-mutation`? Maybe refactor a bit with clearer names?

2023-12-20 09:55 UTC, Roene-JustBetter requested changes

2023-12-20 09:55 UTC, Roene-JustBetter commented on resources/views/components/mutation-button-text.blade.php
> +    class="absolute inset-0 p-[14px]"
You can do this without JIT and this can be on 1 line instead of multiple

2023-12-20 09:55 UTC, Roene-JustBetter commented on resources/views/components/newsletter/input.blade.php
Maybe we should discuss this face to face with @royduin & @jordythevulder to make this more flexible.

2024-01-16 16:19 UTC, jordythevulder requested changes

2024-01-16 16:19 UTC, jordythevulder commented on resources/views/components/newsletter/partials/input.blade.php
> +        <div class="absolute inset-0 p-[14px]" v-if="(mutated || mutating) && !error">
can you use default tailwind values instead of JIT here?

2024-01-29 08:27 UTC, jordythevulder approved these changes

2024-01-29 09:37 UTC, Roene-JustBetter approved these changes

2024-03-12 10:36 UTC, royduin commented on resources/views/components/newsletter/input.blade.php
> +@props(['id' => uniqId('newsletter-'), 'email' => '\'\''])
```suggestion
@props(['id' => uniqId('newsletter-'), 'email' => "''"])
```
More readable?

2024-03-12 13:20 UTC, merged