[2.x] Rename primary to neutral & accent to primary
rapidez/checkout-theme pull request #90
Opened 2024-05-10 09:12 UTC by Jade-GG

https://github.com/rapidez/checkout-theme/issues/88

Given that this is already the case in Confira, might as well waste no time and do it here.

Done with a search&replace. Given that there were already 2 occurrences of the previously undefined `ct-neutral` I hope this doesn't change any `primary` usages that should stay `primary`...

2024-05-14 06:33 UTC, JimmyHoenderdaal approved these changes

2024-05-14 06:36 UTC, Roene-JustBetter requested changes

2024-05-14 06:36 UTC, Roene-JustBetter commented on resources/views/components/button/accent.blade.php
> -<x-rapidez-ct::button {{ $attributes->class('rounded bg-ct-accent font-semibold text-white border-b border-black/20') }}>
Should we change the name to button/primary? @JimmyHoenderdaal @jordythevulder?

2024-09-05 06:55 UTC, jordythevulder approved these changes

2024-09-05 06:58 UTC, royduin commented
Conflicts 😇

2024-09-05 07:31 UTC, Jade-GG commented
Waiting on this for now as it's a pretty annoyingly breaking change to just put out, better to just bundle this with the 3.x update.

2024-09-05 07:31 UTC, closed without merging